### ISSUE TITLE
Knex issue

### ISSUE THREAD

**Issue by bustoutfunk** [bustoutfunk/wellsense-web#11]
I receive Knex issues every time I run gulp:

```
^Camahpour@ubuntu-wellsense:/var/www/wellsense-web$ gulp
[17:28:40] Using gulpfile /var/www/wellsense-web/gulpfile.js
[17:28:40] Starting 'webpack-watch'...
[17:28:40] Starting 'assets-watch'...
[17:28:40] Finished 'assets-watch' after 17 ms
[17:28:40] Starting 'dev-env'...
[17:28:40] Finished 'dev-env' after 49 μs
[17:28:40] Starting 'run'...
[17:28:40] Finished 'run' after 2.28 ms
[17:28:40] [nodemon] 1.10.2
[17:28:40] [nodemon] to restart at any time, enter `rs`
[17:28:40] [nodemon] watching: *.*
[17:28:40] [nodemon] starting `node ./bin/www`
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:3306
Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:3306
Unhandled rejection Error: Pool was destroyed
    at Pool._destroyPool (/var/www/wellsense-web/node_modules/pool2/lib/pool.js:560:20)
    at Pool.<anonymous> (/var/www/wellsense-web/node_modules/pool2/lib/pool.js:474:18)
    at Pool.<anonymous> (/var/www/wellsense-web/node_modules/pool2/lib/pool.js:517:17)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Client.acquireConnection (/var/www/wellsense-web/node_modules/knex/lib/client.js:264:21)
    at /var/www/wellsense-web/node_modules/knex/lib/runner.js:188:47
From previous event:
    at /var/www/wellsense-web/node_modules/knex/lib/runner.js:187:35
From previous event:
    at Runner.ensureConnection (/var/www/wellsense-web/node_modules/knex/lib/runner.js:186:39)
    at Runner.run (/var/www/wellsense-web/node_modules/knex/lib/runner.js:41:44)
    at SchemaBuilder.Target.then (/var/www/wellsense-web/node_modules/knex/lib/interface.js:32:43)
    at new KnexStore (/var/www/wellsense-web/node_modules/connect-session-knex/index.js:108:4)
    at Object.<anonymous> (/var/www/wellsense-web/app.js:37:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/wellsense-web/bin/www:7:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

GET / 304 1175.597 ms - -
GET /css/style.css 304 86.966 ms - -
GET / 200 81.571 ms - 319
[17:28:51] Version: webpack 1.13.2
    Asset     Size  Chunks             Chunk Names
bundle.js  2.04 MB       0  [emitted]  main
[17:28:51] webpack is watching for changes
GET /js/bundle.js 200 755.655 ms - 2041276
webpack built 3b48d08512cc18346373 in 11107ms
GET /favicon.ico 200 5.487 ms - 319
```

Do you know what this issue is?

**Comment by bustoutfunk** [comment]
This seems to have gone away after opening the MySQL port per [this](http://stackoverflow.com/questions/33823440/knexerror-pool2-error-connect-econnrefused) post. I opened the port by running `sudo ufw allow 3306`. Hopefully we won't see this problem again.
